import { Entry, ClassificationResult } from './types'

export const initialEntries: Entry[] = [
  {
    id: 'ent-49281',
    entryNo: 'ENT-49281',
    port: 'LAX',
    productName: 'Lithium-ion Battery Cells',
    description: 'Cylindrical lithium-ion battery cells, 18650 format, 3.7V, for EV applications',
    originCountry: 'China',
    quantity: 50000,
    valueUsd: 142500,
    incoterm: 'FOB',
    htsCode: '8507.60',
    dutyRate: 3.4,
    estimatedDutyUsd: 4845,
    riskLevel: 'High',
    reviewRequired: true,
    reviewReason: 'Section 301 tariffs apply; lithium battery cells subject to CBP examination',
    status: 'Review',
    requiredDocs: ['Commercial Invoice', 'Packing List', 'Bill of Lading', 'MSDS/Safety Data Sheet', 'UN38.3 Test Report'],
    explanation: 'Classified under HTS 8507.60 as lithium-ion accumulators. Subject to Section 301 China tariffs (25%) in addition to base 3.4% duty rate. High risk due to hazmat classification and elevated scrutiny on Chinese-origin EV components.',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ent-49284',
    entryNo: 'ENT-49284',
    port: 'JFK',
    productName: 'Cotton Knit Apparel',
    description: 'Men\'s cotton T-shirts, 100% knit cotton, various sizes, imported for retail',
    originCountry: 'Bangladesh',
    quantity: 12000,
    valueUsd: 36000,
    incoterm: 'CIF',
    htsCode: '6109.10',
    dutyRate: 16.5,
    estimatedDutyUsd: 5940,
    riskLevel: 'Medium',
    reviewRequired: true,
    reviewReason: 'Textile quota monitoring; fiber content verification required',
    status: 'Filing',
    requiredDocs: ['Commercial Invoice', 'Packing List', 'Bill of Lading', 'Textile Declaration', 'Country of Origin Certificate'],
    explanation: 'Classified under HTS 6109.10 as T-shirts of cotton, knitted. Bangladesh benefits from GSP for some goods but apparel remains dutiable at standard rate. Textile monitoring program requires fiber content certification.',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ent-49290',
    entryNo: 'ENT-49290',
    port: 'SEA',
    productName: 'Industrial Ceramics',
    description: 'Refractory ceramic bricks and tiles for industrial kiln applications',
    originCountry: 'Mexico',
    quantity: 8000,
    valueUsd: 28400,
    incoterm: 'DAP',
    htsCode: '6909.19',
    dutyRate: 4.9,
    estimatedDutyUsd: 1392,
    riskLevel: 'Low',
    reviewRequired: false,
    reviewReason: '',
    status: 'Cleared',
    requiredDocs: ['Commercial Invoice', 'Packing List', 'Bill of Lading', 'USMCA Certificate of Origin'],
    explanation: 'Classified under HTS 6909.19 as other ceramic wares for laboratory, industrial use. Mexico-origin goods eligible for USMCA preferential treatment reducing duty to 0% if certificate provided.',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockClassifierResponses: Record<string, ClassificationResult> = {
  'lithium|battery': {
    productName: 'Lithium-ion Battery Cells',
    htsCode: '8507.60',
    dutyRate: 3.4,
    riskLevel: 'High',
    reviewRequired: true,
    reviewReason: 'Section 301 tariffs apply; lithium battery cells subject to CBP examination and hazmat requirements',
    requiredDocs: ['Commercial Invoice', 'Packing List', 'Bill of Lading', 'MSDS/Safety Data Sheet', 'UN38.3 Test Report'],
    explanation: 'Classified under HTS 8507.60 as lithium-ion accumulators. Subject to Section 301 China tariffs (25%) in addition to base 3.4% duty rate. High risk due to hazmat classification and elevated scrutiny on Chinese-origin EV components.',
    port: 'LAX',
    originCountry: 'China',
    quantity: 10000,
    valueUsd: 45000,
    incoterm: 'FOB',
    description: 'Lithium-ion battery cells for consumer electronics applications',
  },
  'cotton|shirt|apparel|knit': {
    productName: 'Cotton Knit Apparel',
    htsCode: '6109.10',
    dutyRate: 16.5,
    riskLevel: 'Medium',
    reviewRequired: true,
    reviewReason: 'Textile quota monitoring; fiber content and country of origin verification required',
    requiredDocs: ['Commercial Invoice', 'Packing List', 'Bill of Lading', 'Textile Declaration', 'Country of Origin Certificate'],
    explanation: 'Classified under HTS 6109.10 as T-shirts of cotton, knitted. Standard duty rate of 16.5% applies. Textile monitoring program requires fiber content certification and origin verification.',
    port: 'JFK',
    originCountry: 'Bangladesh',
    quantity: 5000,
    valueUsd: 15000,
    incoterm: 'CIF',
    description: 'Cotton knit shirts for retail distribution',
  },
  'ceramic': {
    productName: 'Industrial Ceramic Components',
    htsCode: '6909.19',
    dutyRate: 4.9,
    riskLevel: 'Low',
    reviewRequired: false,
    reviewReason: '',
    requiredDocs: ['Commercial Invoice', 'Packing List', 'Bill of Lading'],
    explanation: 'Classified under HTS 6909.19 as other ceramic wares for industrial use. Standard 4.9% duty applies. Low risk entry with straightforward classification.',
    port: 'SEA',
    originCountry: 'Mexico',
    quantity: 2000,
    valueUsd: 8500,
    incoterm: 'DAP',
    description: 'Industrial ceramic components for manufacturing applications',
  },
}
